apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: cody # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: podsrole
  apiGroup: rbac.authorization.k8s.io